package org.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-05T10:31:21.074+03:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "DAXService",
                  wsdlLocation = "classpath:DAXServiceAll.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class DAXService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "DAXService");
    public final static QName BasicHttpBindingIDAXService = new QName("http://tempuri.org/", "BasicHttpBinding_IDAXService");
    static {
        URL url = DAXService.class.getClassLoader().getResource("DAXServiceAll.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DAXService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:DAXServiceAll.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DAXService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DAXService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DAXService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DAXService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DAXService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DAXService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IDAXService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDAXService")
    public IDAXService getBasicHttpBindingIDAXService() {
        return super.getPort(BasicHttpBindingIDAXService, IDAXService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDAXService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDAXService")
    public IDAXService getBasicHttpBindingIDAXService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIDAXService, IDAXService.class, features);
    }

}
