package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-05T10:31:21.033+03:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IDAXService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.ncspintegration.ObjectFactory.class})
public interface IDAXService {

    @WebMethod(operationName = "GetCargoTallyReceiptJournalTables", action = "http://tempuri.org/IDAXService/GetCargoTallyReceiptJournalTables")
    @Action(input = "http://tempuri.org/IDAXService/GetCargoTallyReceiptJournalTables", output = "http://tempuri.org/IDAXService/GetCargoTallyReceiptJournalTablesResponse")
    @RequestWrapper(localName = "GetCargoTallyReceiptJournalTables", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCargoTallyReceiptJournalTables")
    @ResponseWrapper(localName = "GetCargoTallyReceiptJournalTablesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCargoTallyReceiptJournalTablesResponse")
    @WebResult(name = "GetCargoTallyReceiptJournalTablesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfCargoTallyReceiptJournalTable getCargoTallyReceiptJournalTables(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetAcceptanceActs", action = "http://tempuri.org/IDAXService/GetAcceptanceActs")
    @Action(input = "http://tempuri.org/IDAXService/GetAcceptanceActs", output = "http://tempuri.org/IDAXService/GetAcceptanceActsResponse")
    @RequestWrapper(localName = "GetAcceptanceActs", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAcceptanceActs")
    @ResponseWrapper(localName = "GetAcceptanceActsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAcceptanceActsResponse")
    @WebResult(name = "GetAcceptanceActsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfAcceptanceActModel getAcceptanceActs(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetCargoesOnDate", action = "http://tempuri.org/IDAXService/GetCargoesOnDate")
    @Action(input = "http://tempuri.org/IDAXService/GetCargoesOnDate", output = "http://tempuri.org/IDAXService/GetCargoesOnDateResponse")
    @RequestWrapper(localName = "GetCargoesOnDate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCargoesOnDate")
    @ResponseWrapper(localName = "GetCargoesOnDateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCargoesOnDateResponse")
    @WebResult(name = "GetCargoesOnDateResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfCargoOnDateTableModel getCargoesOnDate(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetInventOwners", action = "http://tempuri.org/IDAXService/GetInventOwners")
    @Action(input = "http://tempuri.org/IDAXService/GetInventOwners", output = "http://tempuri.org/IDAXService/GetInventOwnersResponse")
    @RequestWrapper(localName = "GetInventOwners", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventOwners")
    @ResponseWrapper(localName = "GetInventOwnersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventOwnersResponse")
    @WebResult(name = "GetInventOwnersResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfInventOwnerModel getInventOwners();

    @WebMethod(operationName = "GetPortRequestTables", action = "http://tempuri.org/IDAXService/GetPortRequestTables")
    @Action(input = "http://tempuri.org/IDAXService/GetPortRequestTables", output = "http://tempuri.org/IDAXService/GetPortRequestTablesResponse")
    @RequestWrapper(localName = "GetPortRequestTables", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortRequestTables")
    @ResponseWrapper(localName = "GetPortRequestTablesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortRequestTablesResponse")
    @WebResult(name = "GetPortRequestTablesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortRequestTableModel getPortRequestTables(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetAgreementsHeader", action = "http://tempuri.org/IDAXService/GetAgreementsHeader")
    @Action(input = "http://tempuri.org/IDAXService/GetAgreementsHeader", output = "http://tempuri.org/IDAXService/GetAgreementsHeaderResponse")
    @RequestWrapper(localName = "GetAgreementsHeader", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAgreementsHeader")
    @ResponseWrapper(localName = "GetAgreementsHeaderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAgreementsHeaderResponse")
    @WebResult(name = "GetAgreementsHeaderResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfAgreementHeaderModel getAgreementsHeader();

    @WebMethod(operationName = "GetWMSLocations", action = "http://tempuri.org/IDAXService/GetWMSLocations")
    @Action(input = "http://tempuri.org/IDAXService/GetWMSLocations", output = "http://tempuri.org/IDAXService/GetWMSLocationsResponse")
    @RequestWrapper(localName = "GetWMSLocations", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWMSLocations")
    @ResponseWrapper(localName = "GetWMSLocationsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWMSLocationsResponse")
    @WebResult(name = "GetWMSLocationsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfWMSLocation getWMSLocations();

    @WebMethod(operationName = "GetEmployeesTable", action = "http://tempuri.org/IDAXService/GetEmployeesTable")
    @Action(input = "http://tempuri.org/IDAXService/GetEmployeesTable", output = "http://tempuri.org/IDAXService/GetEmployeesTableResponse")
    @RequestWrapper(localName = "GetEmployeesTable", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeesTable")
    @ResponseWrapper(localName = "GetEmployeesTableResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeesTableResponse")
    @WebResult(name = "GetEmployeesTableResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfEmployeeModel getEmployeesTable();

    @WebMethod(operationName = "SetWagonStatus", action = "http://tempuri.org/IDAXService/SetWagonStatus")
    @Action(input = "http://tempuri.org/IDAXService/SetWagonStatus", output = "http://tempuri.org/IDAXService/SetWagonStatusResponse")
    @RequestWrapper(localName = "SetWagonStatus", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetWagonStatus")
    @ResponseWrapper(localName = "SetWagonStatusResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetWagonStatusResponse")
    @WebResult(name = "SetWagonStatusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer setWagonStatus(
        @WebParam(name = "wagonId", targetNamespace = "http://tempuri.org/")
        java.lang.String wagonId,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ncspintegration.PlanTableStatus status,
        @WebParam(name = "operationDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar operationDateTime,
        @WebParam(name = "comment", targetNamespace = "http://tempuri.org/")
        java.lang.String comment,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        java.lang.String user
    );

    @WebMethod(operationName = "GetInventLocations", action = "http://tempuri.org/IDAXService/GetInventLocations")
    @Action(input = "http://tempuri.org/IDAXService/GetInventLocations", output = "http://tempuri.org/IDAXService/GetInventLocationsResponse")
    @RequestWrapper(localName = "GetInventLocations", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventLocations")
    @ResponseWrapper(localName = "GetInventLocationsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventLocationsResponse")
    @WebResult(name = "GetInventLocationsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfInventLocation getInventLocations();

    @WebMethod(operationName = "GetPortTimeSheetsByPeriod", action = "http://tempuri.org/IDAXService/GetPortTimeSheetsByPeriod")
    @Action(input = "http://tempuri.org/IDAXService/GetPortTimeSheetsByPeriod", output = "http://tempuri.org/IDAXService/GetPortTimeSheetsByPeriodResponse")
    @RequestWrapper(localName = "GetPortTimeSheetsByPeriod", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortTimeSheetsByPeriod")
    @ResponseWrapper(localName = "GetPortTimeSheetsByPeriodResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortTimeSheetsByPeriodResponse")
    @WebResult(name = "GetPortTimeSheetsByPeriodResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortTimeSheet getPortTimeSheetsByPeriod(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetPortTimeSheets", action = "http://tempuri.org/IDAXService/GetPortTimeSheets")
    @Action(input = "http://tempuri.org/IDAXService/GetPortTimeSheets", output = "http://tempuri.org/IDAXService/GetPortTimeSheetsResponse")
    @RequestWrapper(localName = "GetPortTimeSheets", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortTimeSheets")
    @ResponseWrapper(localName = "GetPortTimeSheetsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortTimeSheetsResponse")
    @WebResult(name = "GetPortTimeSheetsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortTimeSheet getPortTimeSheets();

    @WebMethod(operationName = "GetInventDims", action = "http://tempuri.org/IDAXService/GetInventDims")
    @Action(input = "http://tempuri.org/IDAXService/GetInventDims", output = "http://tempuri.org/IDAXService/GetInventDimsResponse")
    @RequestWrapper(localName = "GetInventDims", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventDims")
    @ResponseWrapper(localName = "GetInventDimsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventDimsResponse")
    @WebResult(name = "GetInventDimsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfInventDim getInventDims(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetPortEquipments", action = "http://tempuri.org/IDAXService/GetPortEquipments")
    @Action(input = "http://tempuri.org/IDAXService/GetPortEquipments", output = "http://tempuri.org/IDAXService/GetPortEquipmentsResponse")
    @RequestWrapper(localName = "GetPortEquipments", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortEquipments")
    @ResponseWrapper(localName = "GetPortEquipmentsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortEquipmentsResponse")
    @WebResult(name = "GetPortEquipmentsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortEquipment getPortEquipments();

    @WebMethod(operationName = "GetPortTimeSheetOperations", action = "http://tempuri.org/IDAXService/GetPortTimeSheetOperations")
    @Action(input = "http://tempuri.org/IDAXService/GetPortTimeSheetOperations", output = "http://tempuri.org/IDAXService/GetPortTimeSheetOperationsResponse")
    @RequestWrapper(localName = "GetPortTimeSheetOperations", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortTimeSheetOperations")
    @ResponseWrapper(localName = "GetPortTimeSheetOperationsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortTimeSheetOperationsResponse")
    @WebResult(name = "GetPortTimeSheetOperationsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortTimeSheetOperation getPortTimeSheetOperations();

    @WebMethod(operationName = "GetDetailedPlanJours", action = "http://tempuri.org/IDAXService/GetDetailedPlanJours")
    @Action(input = "http://tempuri.org/IDAXService/GetDetailedPlanJours", output = "http://tempuri.org/IDAXService/GetDetailedPlanJoursResponse")
    @RequestWrapper(localName = "GetDetailedPlanJours", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDetailedPlanJours")
    @ResponseWrapper(localName = "GetDetailedPlanJoursResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDetailedPlanJoursResponse")
    @WebResult(name = "GetDetailedPlanJoursResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfCargoDetailedPlanJour getDetailedPlanJours(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetInventBatchs", action = "http://tempuri.org/IDAXService/GetInventBatchs")
    @Action(input = "http://tempuri.org/IDAXService/GetInventBatchs", output = "http://tempuri.org/IDAXService/GetInventBatchsResponse")
    @RequestWrapper(localName = "GetInventBatchs", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventBatchs")
    @ResponseWrapper(localName = "GetInventBatchsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventBatchsResponse")
    @WebResult(name = "GetInventBatchsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfInventBatch getInventBatchs(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetEcoresCategoryes", action = "http://tempuri.org/IDAXService/GetEcoresCategoryes")
    @Action(input = "http://tempuri.org/IDAXService/GetEcoresCategoryes", output = "http://tempuri.org/IDAXService/GetEcoresCategoryesResponse")
    @RequestWrapper(localName = "GetEcoresCategoryes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEcoresCategoryes")
    @ResponseWrapper(localName = "GetEcoresCategoryesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEcoresCategoryesResponse")
    @WebResult(name = "GetEcoresCategoryesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfEcoresCategory getEcoresCategoryes();

    @WebMethod(operationName = "GetPortWorkBrigades", action = "http://tempuri.org/IDAXService/GetPortWorkBrigades")
    @Action(input = "http://tempuri.org/IDAXService/GetPortWorkBrigades", output = "http://tempuri.org/IDAXService/GetPortWorkBrigadesResponse")
    @RequestWrapper(localName = "GetPortWorkBrigades", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortWorkBrigades")
    @ResponseWrapper(localName = "GetPortWorkBrigadesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortWorkBrigadesResponse")
    @WebResult(name = "GetPortWorkBrigadesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortWorkBrigade getPortWorkBrigades();

    @WebMethod(operationName = "GetDeliveryPlan", action = "http://tempuri.org/IDAXService/GetDeliveryPlan")
    @Action(input = "http://tempuri.org/IDAXService/GetDeliveryPlan", output = "http://tempuri.org/IDAXService/GetDeliveryPlanResponse")
    @RequestWrapper(localName = "GetDeliveryPlan", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeliveryPlan")
    @ResponseWrapper(localName = "GetDeliveryPlanResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeliveryPlanResponse")
    @WebResult(name = "GetDeliveryPlanResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortRequestTableModel getDeliveryPlan(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetClientsList", action = "http://tempuri.org/IDAXService/GetClientsList")
    @Action(input = "http://tempuri.org/IDAXService/GetClientsList", output = "http://tempuri.org/IDAXService/GetClientsListResponse")
    @RequestWrapper(localName = "GetClientsList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClientsList")
    @ResponseWrapper(localName = "GetClientsListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClientsListResponse")
    @WebResult(name = "GetClientsListResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfClientListModel getClientsList();

    @WebMethod(operationName = "GetPortCargoTimeSheets", action = "http://tempuri.org/IDAXService/GetPortCargoTimeSheets")
    @Action(input = "http://tempuri.org/IDAXService/GetPortCargoTimeSheets", output = "http://tempuri.org/IDAXService/GetPortCargoTimeSheetsResponse")
    @RequestWrapper(localName = "GetPortCargoTimeSheets", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortCargoTimeSheets")
    @ResponseWrapper(localName = "GetPortCargoTimeSheetsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortCargoTimeSheetsResponse")
    @WebResult(name = "GetPortCargoTimeSheetsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortCargoTimeSheet getPortCargoTimeSheets(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetDefects", action = "http://tempuri.org/IDAXService/GetDefects")
    @Action(input = "http://tempuri.org/IDAXService/GetDefects", output = "http://tempuri.org/IDAXService/GetDefectsResponse")
    @RequestWrapper(localName = "GetDefects", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDefects")
    @ResponseWrapper(localName = "GetDefectsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDefectsResponse")
    @WebResult(name = "GetDefectsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfDefect getDefects();

    @WebMethod(operationName = "GetPlanTables", action = "http://tempuri.org/IDAXService/GetPlanTables")
    @Action(input = "http://tempuri.org/IDAXService/GetPlanTables", output = "http://tempuri.org/IDAXService/GetPlanTablesResponse")
    @RequestWrapper(localName = "GetPlanTables", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPlanTables")
    @ResponseWrapper(localName = "GetPlanTablesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPlanTablesResponse")
    @WebResult(name = "GetPlanTablesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPlanTableModel getPlanTables();

    @WebMethod(operationName = "GetPortEquipmentGroups", action = "http://tempuri.org/IDAXService/GetPortEquipmentGroups")
    @Action(input = "http://tempuri.org/IDAXService/GetPortEquipmentGroups", output = "http://tempuri.org/IDAXService/GetPortEquipmentGroupsResponse")
    @RequestWrapper(localName = "GetPortEquipmentGroups", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortEquipmentGroups")
    @ResponseWrapper(localName = "GetPortEquipmentGroupsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortEquipmentGroupsResponse")
    @WebResult(name = "GetPortEquipmentGroupsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortEquipmentGroup getPortEquipmentGroups();

    @WebMethod(operationName = "GetExMoorings", action = "http://tempuri.org/IDAXService/GetExMoorings")
    @Action(input = "http://tempuri.org/IDAXService/GetExMoorings", output = "http://tempuri.org/IDAXService/GetExMooringsResponse")
    @RequestWrapper(localName = "GetExMoorings", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExMoorings")
    @ResponseWrapper(localName = "GetExMooringsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExMooringsResponse")
    @WebResult(name = "GetExMooringsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfExMooringModel getExMoorings();

    @WebMethod(operationName = "GetPortShiftDayPlans", action = "http://tempuri.org/IDAXService/GetPortShiftDayPlans")
    @Action(input = "http://tempuri.org/IDAXService/GetPortShiftDayPlans", output = "http://tempuri.org/IDAXService/GetPortShiftDayPlansResponse")
    @RequestWrapper(localName = "GetPortShiftDayPlans", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortShiftDayPlans")
    @ResponseWrapper(localName = "GetPortShiftDayPlansResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortShiftDayPlansResponse")
    @WebResult(name = "GetPortShiftDayPlansResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortShiftDayPlanModel getPortShiftDayPlans(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetEcoResProductCategories", action = "http://tempuri.org/IDAXService/GetEcoResProductCategories")
    @Action(input = "http://tempuri.org/IDAXService/GetEcoResProductCategories", output = "http://tempuri.org/IDAXService/GetEcoResProductCategoriesResponse")
    @RequestWrapper(localName = "GetEcoResProductCategories", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEcoResProductCategories")
    @ResponseWrapper(localName = "GetEcoResProductCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEcoResProductCategoriesResponse")
    @WebResult(name = "GetEcoResProductCategoriesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfEcoResProductCategory getEcoResProductCategories();

    @WebMethod(operationName = "GetDispatcherSummarys", action = "http://tempuri.org/IDAXService/GetDispatcherSummarys")
    @Action(input = "http://tempuri.org/IDAXService/GetDispatcherSummarys", output = "http://tempuri.org/IDAXService/GetDispatcherSummarysResponse")
    @RequestWrapper(localName = "GetDispatcherSummarys", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDispatcherSummarys")
    @ResponseWrapper(localName = "GetDispatcherSummarysResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDispatcherSummarysResponse")
    @WebResult(name = "GetDispatcherSummarysResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfDispatcherSummaryModel getDispatcherSummarys(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetPortEquipmentModels", action = "http://tempuri.org/IDAXService/GetPortEquipmentModels")
    @Action(input = "http://tempuri.org/IDAXService/GetPortEquipmentModels", output = "http://tempuri.org/IDAXService/GetPortEquipmentModelsResponse")
    @RequestWrapper(localName = "GetPortEquipmentModels", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortEquipmentModels")
    @ResponseWrapper(localName = "GetPortEquipmentModelsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortEquipmentModelsResponse")
    @WebResult(name = "GetPortEquipmentModelsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortEquipmentModel getPortEquipmentModels();

    @WebMethod(operationName = "GetPortThirdPartyShipsFacts", action = "http://tempuri.org/IDAXService/GetPortThirdPartyShipsFacts")
    @Action(input = "http://tempuri.org/IDAXService/GetPortThirdPartyShipsFacts", output = "http://tempuri.org/IDAXService/GetPortThirdPartyShipsFactsResponse")
    @RequestWrapper(localName = "GetPortThirdPartyShipsFacts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortThirdPartyShipsFacts")
    @ResponseWrapper(localName = "GetPortThirdPartyShipsFactsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortThirdPartyShipsFactsResponse")
    @WebResult(name = "GetPortThirdPartyShipsFactsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortThirdPartyShipsFact getPortThirdPartyShipsFacts(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetPortShips", action = "http://tempuri.org/IDAXService/GetPortShips")
    @Action(input = "http://tempuri.org/IDAXService/GetPortShips", output = "http://tempuri.org/IDAXService/GetPortShipsResponse")
    @RequestWrapper(localName = "GetPortShips", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortShips")
    @ResponseWrapper(localName = "GetPortShipsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortShipsResponse")
    @WebResult(name = "GetPortShipsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortShipTableModel getPortShips();

    @WebMethod(operationName = "GetProcessingOfWagons", action = "http://tempuri.org/IDAXService/GetProcessingOfWagons")
    @Action(input = "http://tempuri.org/IDAXService/GetProcessingOfWagons", output = "http://tempuri.org/IDAXService/GetProcessingOfWagonsResponse")
    @RequestWrapper(localName = "GetProcessingOfWagons", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProcessingOfWagons")
    @ResponseWrapper(localName = "GetProcessingOfWagonsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProcessingOfWagonsResponse")
    @WebResult(name = "GetProcessingOfWagonsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfProcessingOfWagonModel getProcessingOfWagons(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetPortPiers", action = "http://tempuri.org/IDAXService/GetPortPiers")
    @Action(input = "http://tempuri.org/IDAXService/GetPortPiers", output = "http://tempuri.org/IDAXService/GetPortPiersResponse")
    @RequestWrapper(localName = "GetPortPiers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortPiers")
    @ResponseWrapper(localName = "GetPortPiersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortPiersResponse")
    @WebResult(name = "GetPortPiersResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortPierModel getPortPiers();

    @WebMethod(operationName = "GetPortRailRoadLoadingAreas", action = "http://tempuri.org/IDAXService/GetPortRailRoadLoadingAreas")
    @Action(input = "http://tempuri.org/IDAXService/GetPortRailRoadLoadingAreas", output = "http://tempuri.org/IDAXService/GetPortRailRoadLoadingAreasResponse")
    @RequestWrapper(localName = "GetPortRailRoadLoadingAreas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortRailRoadLoadingAreas")
    @ResponseWrapper(localName = "GetPortRailRoadLoadingAreasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortRailRoadLoadingAreasResponse")
    @WebResult(name = "GetPortRailRoadLoadingAreasResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortRailRoadLoadingArea getPortRailRoadLoadingAreas();

    @WebMethod(operationName = "GetAdditionalWorks", action = "http://tempuri.org/IDAXService/GetAdditionalWorks")
    @Action(input = "http://tempuri.org/IDAXService/GetAdditionalWorks", output = "http://tempuri.org/IDAXService/GetAdditionalWorksResponse")
    @RequestWrapper(localName = "GetAdditionalWorks", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAdditionalWorks")
    @ResponseWrapper(localName = "GetAdditionalWorksResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAdditionalWorksResponse")
    @WebResult(name = "GetAdditionalWorksResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfAdditionalWork getAdditionalWorks(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetEcoresCategoryHierarchyes", action = "http://tempuri.org/IDAXService/GetEcoresCategoryHierarchyes")
    @Action(input = "http://tempuri.org/IDAXService/GetEcoresCategoryHierarchyes", output = "http://tempuri.org/IDAXService/GetEcoresCategoryHierarchyesResponse")
    @RequestWrapper(localName = "GetEcoresCategoryHierarchyes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEcoresCategoryHierarchyes")
    @ResponseWrapper(localName = "GetEcoresCategoryHierarchyesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEcoresCategoryHierarchyesResponse")
    @WebResult(name = "GetEcoresCategoryHierarchyesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfEcoresCategoryHierarchy getEcoresCategoryHierarchyes();

    @WebMethod(operationName = "GetCargoTransportInvoiceJours", action = "http://tempuri.org/IDAXService/GetCargoTransportInvoiceJours")
    @Action(input = "http://tempuri.org/IDAXService/GetCargoTransportInvoiceJours", output = "http://tempuri.org/IDAXService/GetCargoTransportInvoiceJoursResponse")
    @RequestWrapper(localName = "GetCargoTransportInvoiceJours", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCargoTransportInvoiceJours")
    @ResponseWrapper(localName = "GetCargoTransportInvoiceJoursResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCargoTransportInvoiceJoursResponse")
    @WebResult(name = "GetCargoTransportInvoiceJoursResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfCargoTransportInvoiceJourModel getCargoTransportInvoiceJours(
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetTosContainerInfo", action = "http://tempuri.org/IDAXService/GetTosContainerInfo")
    @Action(input = "http://tempuri.org/IDAXService/GetTosContainerInfo", output = "http://tempuri.org/IDAXService/GetTosContainerInfoResponse")
    @RequestWrapper(localName = "GetTosContainerInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTosContainerInfo")
    @ResponseWrapper(localName = "GetTosContainerInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTosContainerInfoResponse")
    @WebResult(name = "GetTosContainerInfoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfTosContainerInfo getTosContainerInfo(
        @WebParam(name = "containerNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String containerNumber
    );

    @WebMethod(operationName = "GetPortBerthes", action = "http://tempuri.org/IDAXService/GetPortBerthes")
    @Action(input = "http://tempuri.org/IDAXService/GetPortBerthes", output = "http://tempuri.org/IDAXService/GetPortBerthesResponse")
    @RequestWrapper(localName = "GetPortBerthes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortBerthes")
    @ResponseWrapper(localName = "GetPortBerthesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPortBerthesResponse")
    @WebResult(name = "GetPortBerthesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ncspintegration.ArrayOfPortBerthTable getPortBerthes();
}
